export type BuyerActionRequest = {
  status: { code: string };
  sampleProgram?: { status: string } | null;
  buyerRecommendation?: { status: string; title: string } | null;
  buyerQuotation?: { status: string; quoteNumber: string } | null;
  buyerOrderRequest?: { quoteNumber: string } | null;
  orderChangeRequests?: { id: string; status: string }[];
  fulfillmentCases?: { id: string; status: string; source?: string }[];
  deliveryFeedback?: { action: string }[];
  orderHandoff?: { method: "alibaba_trade_assurance" | "contract"; orderReference: string; orderUrl?: string; fulfillmentStatus?: string } | null;
};

export type BuyerNextAction = { eyebrow: string; title: string; body: string; actionLabel: string; href: string; external?: boolean; tone: "review" | "decision" | "progress" | "closed" };

export function getBuyerNextAction(request: BuyerActionRequest): BuyerNextAction {
  if (request.status.code === "closed") return { eyebrow: "REQUEST CLOSED", title: "Ask Beiqiang if this project should be reopened", body: "The website will not accept new workflow decisions while this request is closed. Use the inquiry reference when contacting the sales team.", actionLabel: "Review contact options", href: "#buyer-contact-actions", tone: "closed" };
  const pendingOrderChange = request.orderChangeRequests?.find((item) => item.status === "awaiting_buyer");
  if (pendingOrderChange) return { eyebrow: "YOUR CONFIRMATION IS REQUIRED", title: `Review order change ${pendingOrderChange.id}`, body: "Compare the proposed critical terms with the current confirmed version. The current version stays active unless you accept the change.", actionLabel: "Review proposed order change", href: "#order-change-review", tone: "decision" };
  const pendingFulfillmentCase = request.fulfillmentCases?.find((item) => item.status === "awaiting_buyer");
  if (pendingFulfillmentCase) return { eyebrow: "FULFILLMENT RESPONSE REQUIRED", title: `Review exception ${pendingFulfillmentCase.id}`, body: "Review the recorded facts, affected scope, expected impact and proposed resolution. Your acknowledgement does not change confirmed commercial terms.", actionLabel: "Review fulfillment exception", href: "#fulfillment-case-review", tone: "decision" };
  if (["shipped", "completed"].includes(request.orderHandoff?.fulfillmentStatus || "") && !request.deliveryFeedback?.some((item) => item.action === "received_as_expected")) return { eyebrow: "SHIPMENT FOLLOW-UP", title: `Confirm receipt or report an issue`, body: "Use the recorded shipment reference to confirm operational receipt or open a structured issue for Beiqiang review.", actionLabel: "Add delivery feedback", href: "#delivery-feedback", tone: "decision" };
  if (request.orderHandoff?.orderReference) return { eyebrow: "FORMAL ORDER HANDOFF", title: `Review order ${request.orderHandoff.orderReference}`, body: "Compare the formal order channel and written eight-item summary with the approved quotation before any production or payment action.", actionLabel: request.orderHandoff.orderUrl ? "Open verified Trade Assurance order" : "Review order handoff", href: request.orderHandoff.orderUrl || "#order-handoff", external: Boolean(request.orderHandoff.orderUrl), tone: "progress" };
  if (request.sampleProgram?.status === "buyer_review") return { eyebrow: "YOUR DECISION IS NEEDED", title: "Review the referenced sample", body: "Check only the written review scope, then approve that sample or describe the exact style, size, color or component revision needed.", actionLabel: "Review sample and respond", href: "#sample-review", tone: "decision" };
  if (request.buyerQuotation?.status === "issued") return { eyebrow: "YOUR DECISION IS NEEDED", title: `Review quotation ${request.buyerQuotation.quoteNumber}`, body: "Check style lines, quantity, price, trade term, validity, payment, packing and sample terms before accepting or requesting a revision.", actionLabel: "Review current quotation", href: "#buyer-quotation", tone: "decision" };
  if (request.buyerQuotation?.status === "buyer_accepted" && !request.buyerOrderRequest) return { eyebrow: "NEXT COMMERCIAL STEP", title: "Provide the formal order setup details", body: "Your quotation acceptance is recorded. Supply the legal purchasing entity, order channel, destination and requested timing so Beiqiang can prepare the formal documents.", actionLabel: "Start order setup request", href: "#order-setup-request", tone: "decision" };
  if (request.buyerOrderRequest) return { eyebrow: "ORDER PREPARATION IN PROGRESS", title: "Beiqiang is verifying your setup request", body: "The request is saved but is not yet a production order. Use the private thread for corrections while the eight written order items are checked.", actionLabel: "Message the sales team", href: "#buyer-message-center", tone: "progress" };
  if (request.buyerQuotation?.status === "buyer_revision_requested") return { eyebrow: "REVISION UNDER REVIEW", title: "Beiqiang is reviewing your commercial targets", body: "Your structured change request is saved. Add only missing style, quantity, packing, timing or trade-term evidence in the private thread while a new version is prepared.", actionLabel: "Add supporting detail", href: "#buyer-message-center", tone: "review" };
  if (request.buyerQuotation?.status === "buyer_declined") return { eyebrow: "QUOTATION DECLINED", title: "Your reason is recorded", body: "Beiqiang will review whether a relevant alternative exists. Use the private thread only if the project direction or commercial requirements change.", actionLabel: "Update the sales team", href: "#buyer-message-center", tone: "review" };
  if (request.buyerRecommendation?.status === "issued") return { eyebrow: "PRODUCT SHORTLIST READY", title: request.buyerRecommendation.title, body: "Review why each product was selected, choose the relevant styles and record whether this shortlist should move into sample or quotation discussion.", actionLabel: "Review recommended products", href: "#buyer-recommendation", tone: "decision" };
  if (request.buyerRecommendation?.status === "buyer_shortlisted") return { eyebrow: "SHORTLIST RECORDED", title: "Turn selected styles into a complete quote request", body: "Add the selected products to your quote list, then provide quantity, colors and size ratio so Beiqiang can review commercially useful terms.", actionLabel: "Review selected styles", href: "#buyer-recommendation", tone: "progress" };
  if (request.buyerRecommendation?.status === "revision_requested") return { eyebrow: "PRODUCT DIRECTION UNDER REVIEW", title: "Clarify the replacement product direction", body: "Your request for different options is recorded. Add any missing market, fit, closure, season, quantity or price-position context in the private message thread.", actionLabel: "Add product criteria", href: "#buyer-message-center", tone: "review" };
  return { eyebrow: "NEXT SOURCING STEP", title: "Complete the information needed for a useful reply", body: "Review the latest buyer-safe update and use the private thread for missing quantity, size, color, sample, destination or timing details.", actionLabel: "Message the sales team", href: "#buyer-message-center", tone: "review" };
}
