export type BuyerActionRequest = {
  status: { code: string };
  sampleProgram?: { status: string } | null;
  buyerRecommendation?: { status: string; title: string } | null;
  buyerQuotation?: { status: string; quoteNumber: string } | null;
  buyerOrderRequest?: { quoteNumber: string } | null;
  orderPreparationPackets?: { status: string; version: number }[];
  orderConfirmationDrafts?: { status: string; version: number }[];
  orderChangeRequests?: { id: string; status: string }[];
  fulfillmentCases?: { id: string; status: string; source?: string }[];
  deliveryFeedback?: { action: string }[];
  repeatOrderOpportunities?: { id: string; status: string; intent: string; nextAction?: string }[];
  meetingRequests?: { id: string; status: string; confirmedSlot?: string; timezone?: string }[];
  orderHandoff?: { method: "alibaba_trade_assurance" | "contract"; orderReference: string; orderUrl?: string; fulfillmentStatus?: string } | null;
};

export type BuyerNextAction = { eyebrow: string; title: string; body: string; actionLabel: string; href: string; external?: boolean; tone: "review" | "decision" | "progress" | "closed" };

export function getBuyerNextAction(request: BuyerActionRequest): BuyerNextAction {
  if (request.status.code === "closed") return { eyebrow: "REQUEST CLOSED", title: "Ask Beiqiang if this project should be reopened", body: "The website will not accept new workflow decisions while this request is closed. Use the inquiry reference when contacting the sales team.", actionLabel: "Review contact options", href: "#buyer-contact-actions", tone: "closed" };
  const pendingOrderChange = request.orderChangeRequests?.find((item) => item.status === "awaiting_buyer");
  if (pendingOrderChange) return { eyebrow: "YOUR CONFIRMATION IS REQUIRED", title: `Review order change ${pendingOrderChange.id}`, body: "Compare the proposed critical terms with the current confirmed version. The current version stays active unless you accept the change.", actionLabel: "Review proposed order change", href: "#order-change-review", tone: "decision" };
  const pendingFulfillmentCase = request.fulfillmentCases?.find((item) => item.status === "awaiting_buyer");
  if (pendingFulfillmentCase) return { eyebrow: "FULFILLMENT RESPONSE REQUIRED", title: `Review exception ${pendingFulfillmentCase.id}`, body: "Review the recorded facts, affected scope, expected impact and proposed resolution. Your acknowledgement does not change confirmed commercial terms.", actionLabel: "Review fulfillment exception", href: "#fulfillment-case-review", tone: "decision" };
  if (["shipped", "completed"].includes(request.orderHandoff?.fulfillmentStatus || "") && !request.deliveryFeedback?.some((item) => item.action === "received_as_expected")) return { eyebrow: "SHIPMENT FOLLOW-UP", title: `Confirm receipt or report an issue`, body: "Use the recorded shipment reference to confirm operational receipt or open a structured issue for Beiqiang review.", actionLabel: "Add delivery feedback", href: "#delivery-feedback", tone: "decision" };
  const repeatOpportunity = request.repeatOrderOpportunities?.find((item) => !["converted", "closed"].includes(item.status));
  if (repeatOpportunity) return { eyebrow: "NEXT SOURCING PROJECT", title: `${repeatOpportunity.id} is ${repeatOpportunity.status.replaceAll("_", " ")}`, body: repeatOpportunity.nextAction || "Beiqiang is reviewing the next sample, shortlist or quotation step.", actionLabel: "Review next-project record", href: "#repeat-order", tone: "progress" };
  if (["shipped", "completed"].includes(request.orderHandoff?.fulfillmentStatus || "")) return { eyebrow: "PLAN THE NEXT ORDER", title: "Start a replenishment or new collection discussion", body: "Share an indicative quantity, purchase window, destination, timing and product direction. Beiqiang will re-check every commercial term before any new order.", actionLabel: "Request next-project review", href: "#repeat-order", tone: "progress" };
  if (request.orderHandoff?.orderReference) return { eyebrow: "FORMAL ORDER HANDOFF", title: `Review order ${request.orderHandoff.orderReference}`, body: "Compare the formal order channel and written eight-item summary with the approved quotation before any production or payment action.", actionLabel: request.orderHandoff.orderUrl ? "Open verified Trade Assurance order" : "Review order handoff", href: request.orderHandoff.orderUrl || "#order-handoff", external: Boolean(request.orderHandoff.orderUrl), tone: "progress" };
  if (request.sampleProgram?.status === "buyer_review") return { eyebrow: "YOUR DECISION IS NEEDED", title: "Review the referenced sample", body: "Check only the written review scope, then approve that sample or describe the exact style, size, color or component revision needed.", actionLabel: "Review sample and respond", href: "#sample-review", tone: "decision" };
  if (request.buyerQuotation?.status === "issued") return { eyebrow: "YOUR DECISION IS NEEDED", title: `Review quotation ${request.buyerQuotation.quoteNumber}`, body: "Check style lines, quantity, price, trade term, validity, payment, packing and sample terms before accepting or requesting a revision.", actionLabel: "Review current quotation", href: "#buyer-quotation", tone: "decision" };
  if (request.buyerQuotation?.status === "buyer_accepted" && !request.buyerOrderRequest) return { eyebrow: "NEXT COMMERCIAL STEP", title: "Provide the formal order setup details", body: "Your quotation acceptance is recorded. Supply the legal purchasing entity, order channel, destination and requested timing so Beiqiang can prepare the formal documents.", actionLabel: "Start order setup request", href: "#order-setup-request", tone: "decision" };
  const packet = request.orderPreparationPackets?.at(-1);
  if (request.buyerOrderRequest && (!packet || packet.status === "needs_revision")) return { eyebrow: packet ? "BUYER REVISION NEEDED" : "NEXT COMMERCIAL STEP", title: packet ? `Revise order-preparation packet V${packet.version + 1}` : "Complete the protected order-preparation packet", body: packet ? "Review Beiqiang's note and submit a new preserved version. This is not yet a production order." : "Connect the billing company, shipping destination, importer direction, requested documents and buyer PO files for human review. This is not yet a production order.", actionLabel: packet ? "Revise protected packet" : "Complete protected packet", href: "#order-preparation-packet", tone: "decision" };
  const confirmation = request.orderConfirmationDrafts?.at(-1);
  if (confirmation?.status === "awaiting_buyer") return { eyebrow: "YOUR LINE-BY-LINE REVIEW IS REQUIRED", title: `Review pre-order confirmation draft V${confirmation.version}`, body: "Compare the eight written items with the accepted quotation, sample decision and PO. Accept only when every item matches, or identify the exact revision fields.", actionLabel: "Review pre-order draft", href: "#pre-order-confirmation", tone: "decision" };
  if (confirmation?.status === "buyer_revision_requested") return { eyebrow: "REVISION UNDER REVIEW", title: `Pre-order draft V${confirmation.version} was returned`, body: "Your exact mismatch fields are preserved. Beiqiang must issue a new version; the previous draft cannot be silently changed.", actionLabel: "Review returned draft", href: "#pre-order-confirmation", tone: "review" };
  if (confirmation?.status === "buyer_accepted") return { eyebrow: "FORMAL DOCUMENT PREPARATION", title: `Pre-order draft V${confirmation.version} is buyer accepted`, body: "Beiqiang must now verify the same terms in the Trade Assurance order or signed contract. Payment and production are not yet authorized by this website acceptance.", actionLabel: "Review accepted draft", href: "#pre-order-confirmation", tone: "progress" };
  if (request.buyerOrderRequest) return { eyebrow: "ORDER PREPARATION IN PROGRESS", title: "Beiqiang is verifying your protected packet", body: "The packet is saved but is not yet a production order. The eight final written order items still require the formal transaction channel.", actionLabel: "Review packet status", href: "#order-preparation-packet", tone: "progress" };
  if (request.buyerQuotation?.status === "buyer_revision_requested") return { eyebrow: "REVISION UNDER REVIEW", title: "Beiqiang is reviewing your commercial targets", body: "Your structured change request is saved. Add only missing style, quantity, packing, timing or trade-term evidence in the private thread while a new version is prepared.", actionLabel: "Add supporting detail", href: "#buyer-message-center", tone: "review" };
  if (request.buyerQuotation?.status === "buyer_declined") return { eyebrow: "QUOTATION DECLINED", title: "Your reason is recorded", body: "Beiqiang will review whether a relevant alternative exists. Use the private thread only if the project direction or commercial requirements change.", actionLabel: "Update the sales team", href: "#buyer-message-center", tone: "review" };
  const activeMeeting = request.meetingRequests?.find((item) => ["pending", "confirmed"].includes(item.status));
  if (activeMeeting?.status === "confirmed") return { eyebrow: "SOURCING MEETING CONFIRMED", title: `${activeMeeting.confirmedSlot || "Confirmed time"} · ${activeMeeting.timezone || "check the recorded time zone"}`, body: "Review the agenda and connection details. The meeting supports discussion; written sample, quotation and formal-order terms remain authoritative.", actionLabel: "Review meeting details", href: "#meeting-request", tone: "progress" };
  if (activeMeeting) return { eyebrow: "MEETING REQUEST UNDER REVIEW", title: `${activeMeeting.id} is awaiting Beiqiang confirmation`, body: "Your proposed local times, time zone and agenda are saved. No calendar booking or attendance is confirmed until Beiqiang approves one option.", actionLabel: "Review meeting request", href: "#meeting-request", tone: "review" };
  if (request.buyerRecommendation?.status === "issued") return { eyebrow: "PRODUCT SHORTLIST READY", title: request.buyerRecommendation.title, body: "Review why each product was selected, choose the relevant styles and record whether this shortlist should move into sample or quotation discussion.", actionLabel: "Review recommended products", href: "#buyer-recommendation", tone: "decision" };
  if (request.buyerRecommendation?.status === "buyer_shortlisted") return { eyebrow: "SHORTLIST RECORDED", title: "Turn selected styles into a complete quote request", body: "Add the selected products to your quote list, then provide quantity, colors and size ratio so Beiqiang can review commercially useful terms.", actionLabel: "Review selected styles", href: "#buyer-recommendation", tone: "progress" };
  if (request.buyerRecommendation?.status === "revision_requested") return { eyebrow: "PRODUCT DIRECTION UNDER REVIEW", title: "Clarify the replacement product direction", body: "Your request for different options is recorded. Add any missing market, fit, closure, season, quantity or price-position context in the private message thread.", actionLabel: "Add product criteria", href: "#buyer-message-center", tone: "review" };
  return { eyebrow: "NEXT SOURCING STEP", title: "Complete the information needed for a useful reply", body: "Review the latest buyer-safe update and use the private thread for missing quantity, size, color, sample, destination or timing details.", actionLabel: "Message the sales team", href: "#buyer-message-center", tone: "review" };
}
