export type WeeklySalesExecution = {
  response: { cohort: number; exactMeasured: number; dateOnlyRecorded: number; awaitingFirstResponse: number; exactCoverageRate: number; recordedContactRate: number; medianHours: number | null; within24Hours: number; within24HourRate: number };
  pipeline: { active: number; ownerAssigned: number; ownerCoverageRate: number; actionScheduled: number; actionCoverageRate: number; overdue: number; overdueRate: number; buyerRepliesAwaiting: number; stale14Days: number; staleRate: number };
  stageRates: { qualified: number; sampleDiscussion: number; quoted: number; quoteAccepted: number; orderSetupRequested: number; orders: number };
  definition: string;
};
export type WeeklyAction = { level: string; title: string; note: string };
export type WeeklyReviewAnalytics = { period: { days: number; from: string; to: string }; funnel: { productViews: number; quoteAdds: number; quoteRequests: number; inquiries: number; qualified: number; sampleDiscussion: number; quoted: number; quoteAccepted: number; orderSetupRequested: number; orders: number }; salesExecution: WeeklySalesExecution; supporting?: { resourceViews?: number; resourceProductOpens?: number; resourceCtas?: number; productShares?: number; lineSheetLeads?: number }; products?: { code: string; views: number; compares: number; specSheets: number; shares: number; quoteAdds: number; inquiries: number }[] };
export type WeeklyReviewSnapshot = { version: number; id: string; capturedAt: string; period: { days: number; from: string; to: string }; salesExecution: WeeklySalesExecution; funnel: WeeklyReviewAnalytics["funnel"]; coverage: { eventsLoaded: number; inquiriesLoaded: number; workspaceActivityLoaded: number; truncated: boolean }; dataBoundary: string };

export function buildWeeklyActions(data: WeeklySalesExecution): WeeklyAction[] {
  return [
    data.pipeline.buyerRepliesAwaiting > 0 ? { level: "紧急", title: `回复 ${data.pipeline.buyerRepliesAwaiting} 个买家最新消息`, note: "逐条打开完整项目，先处理买家明确问题和决定，不用通用群发覆盖原消息。" } : null,
    data.response.awaitingFirstResponse > 0 ? { level: "紧急", title: `承接 ${data.response.awaitingFirstResponse} 个尚无首次联系记录的本期询盘`, note: "核对联系方式和采购资料，发送一个明确下一动作；站外联系后同步日期。" } : null,
    data.pipeline.overdue > 0 ? { level: "高优先", title: `清理 ${data.pipeline.overdue} 个逾期下一动作`, note: "完成、合理重排或按事实关闭，不能只修改日期隐藏逾期。" } : null,
    data.pipeline.ownerCoverageRate < 100 ? { level: "补基础", title: `为 ${data.pipeline.active - data.pipeline.ownerAssigned} 个活跃项目指定负责人`, note: "负责人必须能实际承接下一次回复、样品、报价或订单动作。" } : null,
    data.pipeline.actionCoverageRate < 100 ? { level: "补基础", title: `为 ${data.pipeline.active - data.pipeline.actionScheduled} 个活跃项目补齐下一动作与日期`, note: "下一动作应具体到询问信息、发样、签发报价或书面订单承接。" } : null,
    data.pipeline.stale14Days > 0 ? { level: "复核", title: `复核 ${data.pipeline.stale14Days} 个14天无记录活动项目`, note: "判断继续跟进、等待买家、失单或归档，并记录原因。" } : null,
  ].filter(Boolean).slice(0, 5) as WeeklyAction[];
}

function topProductActions(products: WeeklyReviewAnalytics["products"] = []) {
  const candidates = products.filter((item) => item.views > 0 && item.inquiries === 0).sort((a, b) => b.views - a.views).slice(0, 3);
  return candidates.length ? candidates.map((item) => `- ${item.code}：${item.views}次产品查看、${item.quoteAdds}次询价单加入、0条归因询盘；复核首图后证据、未知项、CTA和询盘资料要求。`) : ["- 当前没有足够的“有查看但无询盘”产品证据；不要仅凭零值批量改页面。"];
}

export function buildWeeklyReviewMarkdown({ analytics, previous = null, generatedAt = new Date().toISOString() }: { analytics: WeeklyReviewAnalytics; previous?: WeeklyReviewSnapshot | null; generatedAt?: string }) {
  const execution = analytics.salesExecution; const actions = buildWeeklyActions(execution); const delta = (current: number, prior: number) => `${current - prior >= 0 ? "+" : ""}${Math.round((current - prior) * 10) / 10}`; const comparison = previous ? [`- 负责人覆盖变化：${delta(execution.pipeline.ownerCoverageRate, previous.salesExecution.pipeline.ownerCoverageRate)}个百分点`, `- 下一动作覆盖变化：${delta(execution.pipeline.actionCoverageRate, previous.salesExecution.pipeline.actionCoverageRate)}个百分点`, `- 逾期项目变化：${delta(execution.pipeline.overdue, previous.salesExecution.pipeline.overdue)}个（减少为改善）`, `- 报价阶段率变化：${delta(execution.stageRates.quoted, previous.salesExecution.stageRates.quoted)}个百分点`, `- 正式订单阶段率变化：${delta(execution.stageRates.orders, previous.salesExecution.stageRates.orders)}个百分点`] : ["- 尚无同周期历史快照，不能判断趋势。"];
  const lines = [
    "# 贝强独立站销售经营周报", "", `生成时间：${generatedAt}`, `数据周期：最近${analytics.period.days}天（${analytics.period.from} 至 ${analytics.period.to}）`, "数据来源：独立站授权分析聚合、真实询盘阶段与站内项目记录。", "", "## Scorecard", `- 产品查看：${analytics.funnel.productViews}`, `- 询价单加入：${analytics.funnel.quoteAdds}`, `- 结构化询价动作：${analytics.funnel.quoteRequests}`, `- 网站询盘：${analytics.funnel.inquiries}`, `- 合格询盘：${analytics.funnel.qualified}`, `- 样品阶段及以后：${analytics.funnel.sampleDiscussion}`, `- 已签发报价：${analytics.funnel.quoted}`, `- 报价已接受：${analytics.funnel.quoteAccepted}`, `- 正式建单申请：${analytics.funnel.orderSetupRequested}`, `- 已确认正式订单：${analytics.funnel.orders}`, "", "## 回复与管道健康", `- 精确首次回复覆盖：${execution.response.exactMeasured}/${execution.response.cohort}（${execution.response.exactCoverageRate}%）`, `- 仅记录联系日期：${execution.response.dateOnlyRecorded}`, `- 首次回复中位时长：${execution.response.medianHours === null ? "无可核验样本" : `${execution.response.medianHours}小时`}`, `- 24小时内回复率：${execution.response.within24HourRate}%（分母仅含精确样本）`, `- 活跃项目：${execution.pipeline.active}`, `- 负责人覆盖：${execution.pipeline.ownerCoverageRate}%`, `- 下一动作覆盖：${execution.pipeline.actionCoverageRate}%`, `- 逾期项目：${execution.pipeline.overdue}`, `- 待回买家消息：${execution.pipeline.buyerRepliesAwaiting}`, `- 14天无记录活动：${execution.pipeline.stale14Days}`, "", "## 与上次同周期快照比较", ...comparison, "", "## Top problems / 本周行动", ...(actions.length ? actions.map((item, index) => `${index + 1}. [${item.level}] ${item.title} — ${item.note}`) : ["1. 当前聚合记录未显示紧急执行缺口；继续核对真实买家、样品、报价和订单。"]), "", "## Product page actions", ...topProductActions(analytics.products), "", "## Keyword / content actions", `- 采购内容阅读：${analytics.supporting?.resourceViews || 0}；产品证据承接：${analytics.supporting?.resourceProductOpens || 0}；结构化询价承接：${analytics.supporting?.resourceCtas || 0}。`, "- 独立站当前不保存搜索词；关键词动作必须结合Search Console或其他可核验查询数据，不能从页面浏览量猜关键词。", "", "## RFQ / follow-up actions", ...(actions.length ? actions.map((item) => `- ${item.title}`) : ["- 保持每个活跃项目有负责人、明确下一动作和日期。"]), "", "## TikTok / competitor checks", "- 本周报不包含TikTok或竞品实时数据；需要时另用对应权威数据和研究流程补充，不把缺失数据写成零表现。", "", "## Next-week task table", "| Task | Owner | Due date | Expected metric impact |", "|---|---|---|---|", ...(actions.length ? actions.map((item) => `| ${item.title.replaceAll("|", "/")} | 项目负责人 | 未来7天 | ${item.level === "紧急" ? "减少待回复/未承接" : "提高管道记录与阶段推进质量"} |`) : ["| 复核真实询盘、样品、报价和订单变化 | 项目负责人 | 未来7天 | 保持记录完整与跟进连续 |"]), "", "## Facts needing confirmation", "- 站外邮件或WhatsApp的具体发送时间，除非有可核验时间戳。", "- 正式订单、付款和收入必须与Alibaba Trade Assurance、合同及财务记录核对。", "- 页面事件、分享、询价单加入和阶段率不是收入、买家批准或预测成交概率。", "", `定义：${execution.definition}`,
  ]; return `${lines.join("\n")}\n`;
}
