import type { Metadata } from "next";
import ChineseLineSheetLeadForm from "../../components/ChineseLineSheetLeadForm";
import ChineseSiteFooter from "../../components/ChineseSiteFooter";
import ChineseSiteHeader from "../../components/ChineseSiteHeader";
import { productCount } from "../../data/catalog-meta";
import { products } from "../../data/products";
import { productNameZh } from "../../data/products-zh";

export const metadata: Metadata = { title: `${productCount}款鞋类Line Sheet｜贝强B2B供应`, description: `申请贝强${productCount}款步行、休闲、针织、套穿和系带鞋英文产品目录，并建立可跟进的采购参考号。`, alternates: { canonical: "https://www.beiqiang.online/zh/line-sheet/", languages: { en: "https://www.beiqiang.online/line-sheet/", "zh-CN": "https://www.beiqiang.online/zh/line-sheet/", "x-default": "https://www.beiqiang.online/line-sheet/" } } };
export default function ChineseLineSheetPage() { const preview = [products[0], products[8], products[23]]; return <main><ChineseSiteHeader englishHref="/line-sheet/" /><section className="line-sheet-hero"><div><p className="eyebrow">B2B产品发现</p><h1>{productCount}款产品。<br />一份可用于选款的目录。</h1><p>在选择样品前查看步行、休闲、针织、套穿和系带产品方向；所有未知项继续保留为待确认。</p><div className="line-sheet-hero-facts"><span>{productCount}款已整理产品</span><span>买家安全事实</span><span>可点击产品页</span><span>可打印A4 PDF</span></div></div><div className="line-sheet-preview" aria-label="产品目录预览">{preview.map((product) => <article key={product.code}><img src={`/catalog-thumbs/${product.slug}.webp`} alt={`${product.code} ${productNameZh(product)}`} loading="lazy" decoding="async" width={640} height={640} /><div><strong>{product.code}</strong><span>{productNameZh(product)}</span></div></article>)}</div></section><section className="line-sheet-value"><div><p className="eyebrow">目录包含什么</p><h2>用于商业选款，不是普通宣传册。</h2></div><div className="line-sheet-value-grid"><article><strong>01</strong><h3>产品方向</h3><p>款号、源款号、穿脱结构、鞋面、尺码方向、颜色和买家适配。</p></article><article><strong>02</strong><h3>证据边界</h3><p>逐款要点及材料、数量和商务报价前仍需确认的内容。</p></article><article><strong>03</strong><h3>下一步</h3><p>连接产品页以及选款、样品、报价和正式订单路径。</p></article></div></section><section className="line-sheet-access"><div className="line-sheet-access-copy"><p className="eyebrow">申请当前版本</p><h2>把浏览行为转成采购需求。</h2><p>提供市场和数量方向。本次申请会保存到与产品询盘相同的私密跟进系统，双方可用一个参考号继续。</p><ul><li>不是零售结账或自动订单</li><li>不虚构价格、产能或认证</li><li>不把宽鞋头写成全店能力</li><li>大货前确认样品和规格</li></ul></div><ChineseLineSheetLeadForm /></section><ChineseSiteFooter /></main>; }
