/* eslint-disable @next/next/no-img-element */
import type { Product } from "../data/products";
import { buyerFitZh, closureZh, factZh, productNameZh, productSummaryZh } from "../data/products-zh";
import AddToQuoteButton from "./AddToQuoteButton";
import { CollectionProductLink } from "./CollectionTracking";

export default function ChineseProductCard({ product, collectionSlug }: { product: Product; collectionSlug?: string }) {
  return <article className="product-card catalog-card"><CollectionProductLink slug={collectionSlug} styleCode={product.code} className="product-image" href={`/zh/products/${product.slug}/`}><img src={`/catalog-thumbs/${product.slug}.webp`} alt={`${product.code} ${productNameZh(product)}`} loading="lazy" decoding="async" width={640} height={640} /></CollectionProductLink><div className="product-meta"><span className="product-tag">{closureZh(product.closure)}</span><span className="product-code">{product.code} / {product.sourceModel}</span></div><h3><CollectionProductLink slug={collectionSlug} styleCode={product.code} href={`/zh/products/${product.slug}/`}>{productNameZh(product)}</CollectionProductLink></h3><p>{productSummaryZh(product)}</p><ul className="product-facts" aria-label={`${product.code}产品要点`}><li>{closureZh(product.closure)}</li><li>{product.size}</li><li>{product.colors.length}种颜色方向</li></ul><dl className="product-card-specs" aria-label={`${product.code}采购信息`}><div><dt>鞋面</dt><dd>{factZh(product.upper)}</dd></div><div><dt>鞋底</dt><dd>{factZh(product.sole)}</dd></div><div><dt>产品视图</dt><dd>{product.images.length}张图片</dd></div></dl><small className="buyer-fit">适合买家：{buyerFitZh(product)}</small><div className="product-card-actions"><CollectionProductLink slug={collectionSlug} styleCode={product.code} className="product-detail-link" href={`/zh/products/${product.slug}/`}>查看产品详情 <span aria-hidden="true">→</span></CollectionProductLink><AddToQuoteButton product={product} compact locale="zh" /></div></article>;
}
