"use client";

import { useState } from "react";

export type WorkspaceAccessRequestRecord = { id: string; name: string; email: string; role: string; purpose: string; status: "pending" | "approved" | "rejected"; requestedAt: string; reviewedAt: string; reviewNote: string };

const roles = [
  ["purchasing", "Purchasing", "采购"], ["merchandising", "Merchandising", "商品 / 选品"], ["operations", "Operations / logistics", "运营 / 物流"], ["finance", "Finance", "财务"], ["management", "Management", "管理层"], ["sourcing_agent", "Sourcing agent", "采购代理"], ["other", "Other verified role", "其他待核实角色"],
];

export default function WorkspaceAccessRequest({ reference, accessCode, requests, locale = "en", onSaved }: { reference: string; accessCode: string; requests: WorkspaceAccessRequestRecord[]; locale?: "en" | "zh"; onSaved: () => Promise<void> }) {
  const zh = locale === "zh"; const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [role, setRole] = useState("purchasing"); const [purpose, setPurpose] = useState(""); const [confirmed, setConfirmed] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(zh ? "申请不会自动授权；贝强会通过已知公司渠道核实。" : "A request never grants access automatically; Beiqiang verifies it through a known company channel.");
  const pending = requests.filter((item) => item.status === "pending");
  async function submit(event: React.FormEvent) {
    event.preventDefault(); setSaving(true); setMessage(zh ? "正在保存同事访问申请……" : "Saving colleague access request…");
    try { const response = await fetch("/api/workspace-access-request", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reference, accessCode, name, email, role, purpose, confirmed }) }); const result = await response.json().catch(() => ({})); if (!response.ok || !result.ok) throw new Error(result.message || (zh ? "申请未能保存。" : "The request could not be saved.")); setName(""); setEmail(""); setRole("purchasing"); setPurpose(""); setConfirmed(false); setMessage(zh ? "申请已提交给贝强核验，目前尚未授予访问权限。" : result.message); await onSaved(); }
    catch (error) { setMessage(error instanceof Error ? error.message : (zh ? "申请未能保存。" : "The request could not be saved.")); } finally { setSaving(false); }
  }
  return <section className="workspace-access-request"><div><p className="eyebrow">{zh ? "采购团队协作" : "BUYING-TEAM COLLABORATION"}</p><h3>{zh ? "申请让公司同事查看项目摘要" : "Request colleague access to this project"}</h3><p>{zh ? "采购、财务、运营或管理同事可以申请各自的邮件登录，但必须由贝强人工核验和授权。" : "A purchasing, finance, operations or management colleague can request their own email login, subject to Beiqiang verification and approval."}</p></div>{requests.length ? <div className="workspace-access-request-history">{[...requests].reverse().map((item) => <article key={item.id}><div><strong>{item.name}</strong><span>{item.email} · {roles.find(([value]) => value === item.role)?.[zh ? 2 : 1] || item.role}</span></div><b>{zh ? ({ pending: "待核验", approved: "已授权", rejected: "未授权" } as const)[item.status] : item.status.replaceAll("_", " ")}</b><small>{zh ? "申请" : "Requested"} {new Date(item.requestedAt).toLocaleString(zh ? "zh-CN" : "en-US")}{item.reviewedAt ? ` · ${zh ? "处理" : "reviewed"} ${new Date(item.reviewedAt).toLocaleString(zh ? "zh-CN" : "en-US")}` : ""}</small>{item.status === "rejected" && item.reviewNote ? <p>{item.reviewNote}</p> : null}</article>)}</div> : null}{pending.length < 5 ? <form onSubmit={submit}><div><label>{zh ? "同事姓名" : "Colleague name"}<input required minLength={2} maxLength={120} value={name} onChange={(event) => setName(event.target.value)} /></label><label>{zh ? "公司邮箱" : "Business email"}<input required type="email" maxLength={180} value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>{zh ? "项目角色" : "Project role"}<select value={role} onChange={(event) => setRole(event.target.value)}>{roles.map(([value, en, cn]) => <option key={value} value={value}>{zh ? cn : en}</option>)}</select></label></div><label>{zh ? "为什么需要查看该项目？" : "Why does this colleague need project access?"}<textarea required minLength={8} maxLength={500} rows={3} value={purpose} onChange={(event) => setPurpose(event.target.value)} placeholder={zh ? "例如：财务负责人需要核对已签发报价和订单准备进度。" : "Example: Finance manager needs to review the issued quotation and order-setup progress."} /></label><label className="workspace-contact-confirm"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} required /><span>{zh ? "我理解提交申请不会自动授权，贝强必须通过已知公司渠道核实后才能开放项目摘要。" : "I understand this request does not grant access. Beiqiang must verify authority through a known company channel before sharing the project summary."}</span></label><button className="button" type="submit" disabled={saving}>{saving ? (zh ? "保存中……" : "Saving…") : (zh ? "提交同事访问申请" : "Request colleague access")}</button></form> : null}<p aria-live="polite">{message}</p><small>{zh ? "即使获批，同事也只能查看该项目的买家安全摘要。报价接受、样品决定、文件、付款与订单动作仍需当前项目私密码或正式交易渠道。" : "Even after approval, the colleague sees only this project's buyer-safe summary. Quotation, sample, file, payment and order actions still require the project code or authoritative transaction channel."}</small></section>;
}
