import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";
import { createAdminFulfillmentCaseHandlers } from "../edgeone-deploy/cloud-functions/api/admin/fulfillment-case.js";
import { createFulfillmentCaseResponseHandler } from "../edgeone-deploy/cloud-functions/api/fulfillment-case-response.js";
import { createDeliveryFeedbackHandler } from "../edgeone-deploy/cloud-functions/api/delivery-feedback.js";

const reference = "BQ-20260823-ABCDEF12"; const accessCode = "0123456789ABCDEF0123";
function record() { return { reference, receivedAt: "2026-08-23T08:00:00.000Z", status: "order_confirmed", name: "Jane", company: "Buyer Co", email: "buyer@example.com", owner: "Sales A", accessTokenHash: createHash("sha256").update(accessCode).digest("hex"), orderHandoff: { orderReference: "TA-1", fulfillmentStatus: "production", carrier: "", trackingNumber: "" }, fulfillmentCases: [], deliveryFeedback: [] }; }
const adminPayload = { reference, receivedAt: "2026-08-23T08:00:00.000Z", category: "production_delay", title: "Production timing review", facts: "Material arrival was recorded later than planned.", affectedScope: "BQ009 / 500 pairs", impact: "The planned inspection date may move.", proposedResolution: "Confirm a revised inspection date after the material check.", responseDue: "2026-08-26", createdBy: "Sales A" };

test("admin saves a fulfillment case before emailing and never emails the private code", async () => {
  const source = record(); let saved; let savedBeforeMail = false; let mail;
  const handlers = createAdminFulfillmentCaseHandlers({ getStoreImpl: () => ({ get: async () => source, setJSON: async (key, value) => { saved = structuredClone(value); } }), createTransportImpl: () => ({ sendMail: async (value) => { savedBeforeMail = Boolean(saved?.fulfillmentCases?.length); mail = value; } }), nowImpl: () => new Date("2026-08-23T10:00:00.000Z"), randomBytesImpl: () => Buffer.from("abcdef012345", "hex") });
  const request = new Request("https://www.beiqiang.online/api/admin/fulfillment-case", { method: "POST", headers: { Authorization: "Bearer correct", "Content-Type": "application/json" }, body: JSON.stringify(adminPayload) }); const result = await handlers.onRequestPost({ request, env: { INQUIRY_ADMIN_TOKEN: "correct", SMTP_PASS: "configured" } }); const body = await result.json();
  assert.equal(result.status, 201); assert.equal(body.case.id, "FLC-ABCDEF012345"); assert.equal(savedBeforeMail, true); assert.equal(saved.fulfillmentCases[0].notificationStatus, "sent"); assert.match(mail.text, /does not change the confirmed order/i); assert.equal(mail.text.includes(accessCode), false);
});

test("buyer can request a revision once and the response is saved before sales email", async () => {
  const source = record(); source.fulfillmentCases = [{ ...adminPayload, id: "FLC-ABCDEF012345", status: "awaiting_buyer", createdAt: "2026-08-23T10:00:00.000Z" }]; let saved; let savedBeforeMail = false;
  const handler = createFulfillmentCaseResponseHandler({ getStoreImpl: () => ({ get: async () => source, setJSON: async (key, value) => { saved = structuredClone(value); } }), createTransportImpl: () => ({ sendMail: async () => { savedBeforeMail = saved.fulfillmentCases[0].status === "buyer_revision_requested"; } }), nowImpl: () => new Date("2026-08-23T11:00:00.000Z") });
  const request = () => new Request("https://www.beiqiang.online/api/fulfillment-case-response", { method: "POST", headers: { Origin: "https://www.beiqiang.online", "Content-Type": "application/json" }, body: JSON.stringify({ reference, accessCode, caseId: "FLC-ABCDEF012345", decision: "request_revision", note: "Please keep the original inspection date." }) }); const result = await handler({ request: request(), env: { SMTP_PASS: "configured" } }); assert.equal(result.status, 200); assert.equal(savedBeforeMail, true); assert.match(saved.nextAction, /pause affected action/i); source.fulfillmentCases = saved.fulfillmentCases; assert.equal((await handler({ request: request(), env: {} })).status, 409);
});

test("delivery receipt is available only after shipment and cannot be recorded twice", async () => {
  const source = record(); let saved; const handler = createDeliveryFeedbackHandler({ getStoreImpl: () => ({ get: async () => source, setJSON: async (key, value) => { saved = structuredClone(value); } }), nowImpl: () => new Date("2026-08-23T12:00:00.000Z"), randomBytesImpl: () => Buffer.from("abcdef012345", "hex") }); const request = () => new Request("https://www.beiqiang.online/api/delivery-feedback", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reference, accessCode, action: "received_as_expected", note: "Cartons received." }) }); assert.equal((await handler({ request: request(), env: {} })).status, 409); source.orderHandoff.fulfillmentStatus = "shipped"; source.orderHandoff.trackingNumber = "TRACK-1"; const result = await handler({ request: request(), env: {} }); assert.equal(result.status, 200); assert.equal(saved.deliveryFeedback[0].trackingReference, "TRACK-1"); assert.equal(saved.status, "order_confirmed"); assert.match(saved.buyerUpdate, /does not waive/i); source.deliveryFeedback = saved.deliveryFeedback; assert.equal((await handler({ request: request(), env: {} })).status, 409);
});

test("buyer issue report creates an internal fulfillment case without changing order terms", async () => {
  const source = record(); source.orderHandoff.fulfillmentStatus = "completed"; source.orderHandoff.trackingNumber = "TRACK-2"; let saved; let savedBeforeMail = false; const handler = createDeliveryFeedbackHandler({ getStoreImpl: () => ({ get: async () => source, setJSON: async (key, value) => { saved = structuredClone(value); } }), createTransportImpl: () => ({ sendMail: async () => { savedBeforeMail = saved.fulfillmentCases[0].status === "open_internal"; } }), nowImpl: () => new Date("2026-08-23T13:00:00.000Z"), randomBytesImpl: () => Buffer.from("abcdef012345", "hex") }); const request = new Request("https://www.beiqiang.online/api/delivery-feedback", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reference, accessCode, action: "report_issue", category: "packing_labeling", note: "Two cartons show a different outer mark." }) }); const result = await handler({ request, env: { SMTP_PASS: "configured" } }); assert.equal(result.status, 201); assert.equal(savedBeforeMail, true); assert.equal(saved.fulfillmentCases[0].source, "buyer"); assert.equal(saved.fulfillmentCases[0].status, "open_internal"); assert.equal(saved.orderHandoff.orderReference, "TA-1");
});

test("admin resolution preserves case history", async () => {
  const source = record(); source.fulfillmentCases = [{ id: "FLC-ABCDEF012345", status: "open_internal", title: "Buyer issue" }]; let saved; const handlers = createAdminFulfillmentCaseHandlers({ getStoreImpl: () => ({ get: async () => source, setJSON: async (key, value) => { saved = structuredClone(value); } }), nowImpl: () => new Date("2026-08-23T14:00:00.000Z") }); const request = new Request("https://www.beiqiang.online/api/admin/fulfillment-case", { method: "PATCH", headers: { Authorization: "Bearer correct", "Content-Type": "application/json" }, body: JSON.stringify({ reference, receivedAt: source.receivedAt, caseId: "FLC-ABCDEF012345", resolutionNote: "Outer marks were replaced and buyer received photo evidence." }) }); const result = await handlers.onRequestPatch({ request, env: { INQUIRY_ADMIN_TOKEN: "correct" } }); assert.equal(result.status, 200); assert.equal(saved.fulfillmentCases.length, 1); assert.equal(saved.fulfillmentCases[0].status, "resolved"); assert.ok(saved.fulfillmentCases[0].resolvedAt);
});
