import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";
import { createInquiryStatusHandler } from "../edgeone-deploy/cloud-functions/api/inquiry-status.js";

const reference = "BQ-20260823-ABCDEF12";
const accessCode = "0123456789ABCDEF0123";
const record = {
  reference, receivedAt: "2026-08-23T08:00:00.000Z", status: "quoted", styleCode: "BQ001, BQ009", styleLabel: "Two styles",
  projectPath: "base_style_adaptation", quantity: "800 pairs", preferredTradeTerm: "FCA", deliveryDestination: "Los Angeles, CA 90001", deliveryTiming: "Arrival in November", accessTokenHash: createHash("sha256").update(accessCode).digest("hex"),
  internalNote: "Never expose this", nextAction: "Internal only", buyerUpdate: "Quotation details were sent by email.",
  adaptationBrief: { intent: "private_label", artworkStatus: "vector_ready", brandingPlacement: "Tongue label", colorDirection: "Buyer requests navy; material subject to review", packingLabeling: "Buyer barcode label", internalCapability: "never expose" },
  items: [{ code: "BQ001", name: "Wide Toe Box Knit Slip-On", quantity: "400", colors: "Black", sizes: "EU 36-46" }],
  attachments: [{ id: "abcdef0123456789abcd", key: "inquiry-files/private/internal-key.pdf", name: "brand-tech-pack.pdf", size: 2048, uploadedAt: "2026-08-23T09:00:00.000Z" }],
  messages: [{ id: "MSG-ABC", sender: "sales", body: "Please confirm the sample size.", sentAt: "2026-08-23T09:15:00.000Z", notificationSent: true, internalRouting: "never expose" }],
  workspaceAccessRequests: [{ id: "BWR-ABCDEF012345", name: "Alex Finance", email: "finance@buyer.com", role: "finance", purpose: "Review quotation", status: "pending", requestedAt: "2026-08-23T09:16:00.000Z", reviewedBy: "never expose", notificationStatus: "sent" }],
  sampleRequests: [{ id: "BSR-ABCDEF012345", styleCodes: ["BQ001"], sampleType: "existing_style", quantity: "1 pair", sizes: "EU 42", colors: "Black", evaluationPurpose: "Fit review", customizationTarget: "", acceptanceFocus: "Fit and visible workmanship", targetBulkQuantity: "500 pairs", shippingCountry: "Germany", shippingCity: "Hamburg", courierAccountAvailable: true, requestedTiming: "September 2026", status: "rejected", submittedAt: "2026-08-23T09:17:00.000Z", reviewedAt: "2026-08-23T09:18:00.000Z", reviewedBy: "never expose", reviewNote: "Requested timing cannot be supported.", sampleReference: "", notificationStatus: "sent" }],
  meetingRequests: [{ id: "BMR-ABCDEF012345", meetingType: "quotation_review", preferredChannel: "video_call", timezone: "Europe/Berlin", preferredSlots: ["2026-09-02T10:00", "2026-09-03T15:30"], agenda: "Review quotation terms", attendees: "Purchasing manager", language: "en", status: "confirmed", submittedAt: "2026-08-23T09:19:00.000Z", confirmedSlot: "2026-09-02T10:00", confirmedChannel: "video_call", meetingLink: "https://meet.google.com/abc-defg-hij", reviewNote: "Prepare current quotation.", reviewedAt: "2026-08-23T09:20:00.000Z", reviewedBy: "never expose", notificationStatus: "sent", internalCalendarId: "never expose" }],
  orderDocuments: [{ id: "abcdef0123456789abcd", key: "order-documents/private/qc.pdf", name: "qc.pdf", title: "Quality inspection summary", category: "quality_inspection", note: "For the referenced batch", contentType: "application/pdf", size: 100, uploadedAt: "2026-08-23T09:20:00.000Z", internalApproval: "never expose" }],
  sampleProgram: { status: "buyer_review", sampleReference: "BQ001-S1-R1", styleCodes: "BQ001", quantity: "1 pair", sizes: "EU 42", colors: "Black", purpose: "Fit review", reviewScope: "Fit and visible workmanship only", deliverables: "One physical pair", acceptanceCriteria: "Visible workmanship and fit comments", exclusions: "Bulk consistency and laboratory tests", reviewRounds: [{ round: 1, sampleReference: "BQ001-S1-R1", styleCodes: "BQ001", purpose: "Fit review", reviewScope: "Fit and visible workmanship only", deliverables: "One physical pair", acceptanceCriteria: "Visible workmanship and fit comments", exclusions: "Bulk consistency and laboratory tests", status: "awaiting_buyer", openedAt: "2026-08-23T09:25:00.000Z", internalRoundNote: "never expose" }], currency: "USD", sampleCharge: "50.00", chargeStatus: "paid", paidAt: "2026-08-20", courier: "DHL", trackingNumber: "DHL123", shippedAt: "2026-08-21", expectedDelivery: "2026-08-24", note: "Review this reference sample.", updatedAt: "2026-08-23T09:25:00.000Z", history: [{ actor: "Internal only" }], internalCost: "never expose" },
  orderHandoff: { method: "alibaba_trade_assurance", orderReference: "TA-2026-001", orderUrl: "https://trade.alibaba.com/order/example", confirmedAt: "2026-08-23", note: "Review the order details before payment.", paymentCurrency: "USD", paymentMilestones: [{ id: "PM-1", label: "Deposit", amount: "980.00", dueDate: "2026-08-25", status: "paid", paidAt: "2026-08-24", reference: "TA-PAY-1", note: "Recorded", internalBankData: "never expose" }], orderChecklist: { productSpecification: "SPEC-1", sampleDecision: "Sample approved", quantitySizeRatio: "500 pairs / PO-1", colorsMaterials: "Black / MAT-1", packingLabeling: "PK-1", priceTradeTerm: "Q1 / FOB Xiamen", paymentTerms: "30/70", deliveryWindow: "31 days" } },
  orderVersions: [{ version: 1, acceptedAt: "2026-08-23T11:00:00.000Z", acceptedBy: "Internal salesperson", source: "initial_confirmation", orderHandoff: { method: "contract", orderReference: "CT-1", orderUrl: "", confirmedAt: "2026-08-23", note: "Current terms", paymentCurrency: "USD", paymentMilestones: [], orderChecklist: { productSpecification: "SPEC-1", sampleDecision: "Approved", quantitySizeRatio: "500 pairs", colorsMaterials: "Black", packingLabeling: "PK-1", priceTradeTerm: "Q1 / FOB Xiamen", paymentTerms: "30/70", deliveryWindow: "31 days" }, internalData: "never expose" } }],
  orderChangeRequests: [{ id: "OCR-ABCDEF012345", status: "awaiting_buyer", reason: "Quantity changed after PO review", changedFields: ["quantitySizeRatio"], baseVersion: 1, proposedHandoff: { method: "contract", orderReference: "CT-1-R1", orderUrl: "", confirmedAt: "2026-08-23", note: "Proposed terms", paymentCurrency: "USD", paymentMilestones: [], orderChecklist: { productSpecification: "SPEC-1", sampleDecision: "Approved", quantitySizeRatio: "600 pairs", colorsMaterials: "Black", packingLabeling: "PK-1", priceTradeTerm: "Q1 / FOB Xiamen", paymentTerms: "30/70", deliveryWindow: "31 days" }, internalData: "never expose" }, createdAt: "2026-08-23T12:00:00.000Z", createdBy: "Internal salesperson" }],
  quotations: [{ quoteNumber: `${reference}-Q1`, version: "1", currency: "USD", tradeTerm: "FOB", validUntil: "2026-09-15", leadTime: "Subject to confirmation", paymentTerms: "To be confirmed", packing: "To be confirmed", sampleTerms: "Discuss first", notes: "First issued version", lines: [{ code: "BQ001", description: "Black", quantity: "400", unitPrice: "10.20" }], status: "superseded", issuedAt: "2026-08-22T09:30:00.000Z", buyerDecision: "revision_requested", buyerNote: "Review price for 800 pairs", revisionBrief: { reasons: ["unit_price"], affectedCodes: ["BQ001"], targetQuantity: "800 pairs", targetUnitPrice: "USD 9.80", targetTradeTerm: "FOB", requestedDelivery: "", requestedPayment: "", requestedPacking: "", requestedSample: "" }, internalCost: "never expose" }, { quoteNumber: `${reference}-Q2`, version: "2", currency: "USD", tradeTerm: "FOB", validUntil: "2026-09-30", leadTime: "Subject to confirmation", paymentTerms: "To be confirmed", packing: "To be confirmed", sampleTerms: "Discuss first", notes: "Sample approval required", lines: [{ code: "BQ001", description: "Black", quantity: "800", unitPrice: "9.80" }], status: "buyer_revision_requested", issuedAt: "2026-08-23T09:30:00.000Z", buyerDecision: "revision_requested", revisionBrief: { reasons: ["unit_price"], affectedCodes: ["BQ001"], targetQuantity: "1000 pairs", targetUnitPrice: "USD 9.20", targetTradeTerm: "FOB", requestedDelivery: "", requestedPayment: "", requestedPacking: "", requestedSample: "" }, internalCost: "never expose" }, { quoteNumber: `${reference}-Q3-DRAFT`, version: "3", currency: "USD", tradeTerm: "FOB", validUntil: "2026-10-30", lines: [], status: "draft", internalCost: "never expose" }],
  buyerOrderRequests: [{ id: "OSR-1", quoteNumber: `${reference}-Q2`, preferredOrderChannel: "alibaba_trade_assurance", legalCompanyName: "Buyer Legal Co", purchasingContact: "Jane", purchaseOrderReference: "PO-1", destination: "Hamburg, Germany", requestedWindow: "November 2026", instructions: "Use packing reference", status: "submitted", submittedAt: "2026-08-23T10:00:00.000Z", internalRisk: "never expose" }],
  recommendationSets: [{ id: "REC-ABCDEF012345", title: "Three commercial directions", introduction: "Selected for the buyer's stated channel.", items: [{ code: "BQ001", reason: "Verified wide-toe direction." }, { code: "BQ009", reason: "Athletic mesh direction." }], nextStep: "Choose one or two styles for sampling.", status: "issued", issuedAt: "2026-08-23T10:30:00.000Z", issuedBy: "Internal salesperson", internalMargin: "never expose" }],
};

function request(code = accessCode) { return new Request(`https://www.beiqiang.online/api/inquiry-status?reference=${reference}&accessCode=${code}`); }

test("returns only the buyer-safe inquiry status fields", async () => {
  const handler = createInquiryStatusHandler({ getStoreImpl: () => ({ get: async () => record }) });
  const result = await handler({ request: request() }); const body = await result.json();
  assert.equal(result.status, 200); assert.equal(body.request.status.code, "quotation_stage");
  assert.equal(body.request.items[0].code, "BQ001"); assert.equal(body.request.buyerUpdate, "Quotation details were sent by email.");
  assert.equal(body.request.preferredTradeTerm, "FCA"); assert.match(body.request.deliveryDestination, /Los Angeles/);
  assert.deepEqual(body.request.adaptationBrief, { intent: "private_label", artworkStatus: "vector_ready", brandingPlacement: "Tongue label", colorDirection: "Buyer requests navy; material subject to review", packingLabeling: "Buyer barcode label" }); assert.equal(body.request.adaptationBrief.internalCapability, undefined);
  assert.equal(body.request.attachments[0].name, "brand-tech-pack.pdf"); assert.equal(body.request.attachments[0].key, undefined);
  assert.equal(body.request.messages[0].body, "Please confirm the sample size."); assert.equal(body.request.messages[0].internalRouting, undefined); assert.equal(body.request.messages[0].notificationSent, undefined);
  assert.equal(body.request.workspaceAccessRequests[0].email, "finance@buyer.com"); assert.equal(body.request.workspaceAccessRequests[0].status, "pending"); assert.equal(body.request.workspaceAccessRequests[0].reviewedBy, undefined); assert.equal(body.request.workspaceAccessRequests[0].notificationStatus, undefined);
  assert.equal(body.request.sampleRequests[0].id, "BSR-ABCDEF012345"); assert.equal(body.request.sampleRequests[0].status, "rejected"); assert.match(body.request.sampleRequests[0].reviewNote, /timing/); assert.equal(body.request.sampleRequests[0].reviewedBy, undefined); assert.equal(body.request.sampleRequests[0].notificationStatus, undefined);
  assert.equal(body.request.meetingRequests[0].id, "BMR-ABCDEF012345"); assert.equal(body.request.meetingRequests[0].status, "confirmed"); assert.equal(body.request.meetingRequests[0].meetingLink, "https://meet.google.com/abc-defg-hij"); assert.equal(body.request.meetingRequests[0].reviewedBy, undefined); assert.equal(body.request.meetingRequests[0].notificationStatus, undefined); assert.equal(body.request.meetingRequests[0].internalCalendarId, undefined);
  assert.equal(body.request.orderDocuments[0].title, "Quality inspection summary"); assert.equal(body.request.orderDocuments[0].key, undefined); assert.equal(body.request.orderDocuments[0].internalApproval, undefined);
  assert.equal(body.request.sampleProgram.styleCodes, "BQ001"); assert.equal(body.request.sampleProgram.sampleReference, "BQ001-S1-R1"); assert.equal(body.request.sampleProgram.reviewScope, "Fit and visible workmanship only"); assert.match(body.request.sampleProgram.exclusions, /Bulk consistency/); assert.equal(body.request.sampleProgram.reviewRounds[0].internalRoundNote, undefined); assert.equal(body.request.sampleProgram.history, undefined); assert.equal(body.request.sampleProgram.internalCost, undefined);
  assert.equal(body.request.orderHandoff.orderReference, "TA-2026-001"); assert.match(body.request.orderHandoff.orderUrl, /^https:\/\/trade\.alibaba\.com\//);
  assert.equal(body.request.orderHandoff.paymentMilestones[0].label, "Deposit"); assert.equal(body.request.orderHandoff.paymentMilestones[0].internalBankData, undefined);
  assert.equal(body.request.orderHandoff.orderChecklist.productSpecification, "SPEC-1"); assert.equal(Object.keys(body.request.orderHandoff.orderChecklist).length, 8);
  assert.equal(body.request.orderVersions[0].version, 1); assert.equal(body.request.orderVersions[0].acceptedBy, "Beiqiang / formal order record"); assert.equal(body.request.orderVersions[0].orderHandoff.internalData, undefined);
  assert.equal(body.request.orderChangeRequests[0].status, "awaiting_buyer"); assert.equal(body.request.orderChangeRequests[0].proposedHandoff.orderChecklist.quantitySizeRatio, "600 pairs"); assert.equal(body.request.orderChangeRequests[0].createdBy, undefined); assert.equal(body.request.orderChangeRequests[0].proposedHandoff.internalData, undefined);
  assert.equal(body.request.buyerQuotation.quoteNumber, `${reference}-Q2`); assert.equal(body.request.buyerQuotation.internalCost, undefined); assert.deepEqual(body.request.buyerQuotation.revisionBrief.affectedCodes, ["BQ001"]);
  assert.equal(body.request.quotationHistory.length, 2); assert.equal(body.request.quotationHistory[0].quoteNumber, `${reference}-Q1`); assert.equal(body.request.quotationHistory[0].lines[0].unitPrice, "10.20"); assert.equal(body.request.quotationHistory[0].internalCost, undefined); assert.equal(body.request.quotationHistory.some((quote) => quote.quoteNumber.includes("DRAFT")), false);
  assert.equal(body.request.buyerOrderRequest.legalCompanyName, "Buyer Legal Co"); assert.equal(body.request.buyerOrderRequest.internalRisk, undefined);
  assert.equal(body.request.buyerRecommendation.items[1].code, "BQ009"); assert.equal(body.request.buyerRecommendation.issuedBy, undefined); assert.equal(body.request.buyerRecommendation.internalMargin, undefined);
  assert.equal(body.request.internalNote, undefined); assert.equal(body.request.nextAction, undefined); assert.equal(body.request.accessTokenHash, undefined);
});

test("rejects an incorrect inquiry status access code", async () => {
  const handler = createInquiryStatusHandler({ getStoreImpl: () => ({ get: async () => record }) });
  const result = await handler({ request: request("FFFFFFFFFFFFFFFFFFFF") });
  assert.equal(result.status, 404);
});
