import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";
import { createRepeatOrderRequestHandler } from "../edgeone-deploy/cloud-functions/api/repeat-order-request.js";
import { createAdminRepeatOrderHandler } from "../edgeone-deploy/cloud-functions/api/admin/repeat-order-opportunity.js";

const reference = "BQ-20260823-ABCDEF12"; const accessCode = "0123456789ABCDEF0123";
function record() { return { reference, receivedAt: "2026-08-23T08:00:00.000Z", status: "order_confirmed", name: "Jane", company: "Buyer Co", email: "buyer@example.com", owner: "Sales A", accessTokenHash: createHash("sha256").update(accessCode).digest("hex"), orderHandoff: { orderReference: "TA-1", fulfillmentStatus: "shipped" }, repeatOrderOpportunities: [] }; }
function payload(overrides = {}) { return { reference, accessCode, intent: "repeat_same_order", styleCodes: ["BQ009"], indicativeQuantity: "1,000 pairs", purchaseWindow: "within_60_days", requestedTiming: "Target shipment in October", destination: "Hamburg, Germany", changes: "Review black and navy ratio", requirements: "Mixed sizes to discuss", buyerConfirmation: true, ...overrides }; }
function buyerRequest(body = payload()) { return new Request("https://www.beiqiang.online/api/repeat-order-request", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); }

test("saves a repeat-order opportunity before sales and buyer notifications", async () => {
  const source = record(); let saved; const mailSnapshots = [];
  const handler = createRepeatOrderRequestHandler({ getStoreImpl: () => ({ get: async () => source, setJSON: async (key, value) => { saved = structuredClone(value); } }), createTransportImpl: () => ({ sendMail: async (mail) => { mailSnapshots.push({ saved: Boolean(saved?.repeatOrderOpportunities?.length), mail }); } }), nowImpl: () => new Date("2026-08-23T10:00:00.000Z"), randomBytesImpl: () => Buffer.from("abcdef012345", "hex") }); const result = await handler({ request: buyerRequest(), env: { SMTP_PASS: "configured" } }); const body = await result.json();
  assert.equal(result.status, 201); assert.equal(body.opportunityId, "ROP-ABCDEF012345"); assert.equal(mailSnapshots.length, 2); assert.equal(mailSnapshots.every((item) => item.saved), true); assert.equal(mailSnapshots.some((item) => item.mail.text.includes(accessCode)), false); assert.equal(saved.repeatOrderOpportunities[0].notificationStatus, "sales_and_buyer_sent"); assert.match(mailSnapshots[1].mail.text, /not a purchase order/i);
});

test("repeat-order request requires shipment, buyer confirmation and styles when relevant", async () => {
  const source = record(); source.orderHandoff.fulfillmentStatus = "production"; const handler = createRepeatOrderRequestHandler({ getStoreImpl: () => ({ get: async () => source, setJSON: async () => assert.fail("must not write") }) }); assert.equal((await handler({ request: buyerRequest(), env: {} })).status, 409); source.orderHandoff.fulfillmentStatus = "shipped"; assert.equal((await handler({ request: buyerRequest(payload({ buyerConfirmation: false })), env: {} })).status, 400); assert.equal((await handler({ request: buyerRequest(payload({ styleCodes: [] })), env: {} })).status, 400);
});

test("only one active next-project opportunity can exist", async () => {
  const source = record(); source.repeatOrderOpportunities = [{ id: "ROP-OLD", status: "qualified" }]; const handler = createRepeatOrderRequestHandler({ getStoreImpl: () => ({ get: async () => source, setJSON: async () => assert.fail("must not write") }) }); assert.equal((await handler({ request: buyerRequest(), env: {} })).status, 409);
});

test("admin progresses the opportunity with append-only history", async () => {
  const source = record(); source.repeatOrderOpportunities = [{ id: "ROP-ABCDEF012345", status: "submitted", owner: "Sales A", nextAction: "Qualify", nextActionDue: "2026-08-23", history: [{ from: "", to: "submitted", changedAt: "2026-08-23T10:00:00.000Z", actor: "Buyer" }] }]; let saved; const handler = createAdminRepeatOrderHandler({ getStoreImpl: () => ({ get: async () => source, setJSON: async (key, value) => { saved = structuredClone(value); } }), nowImpl: () => new Date("2026-08-23T11:00:00.000Z") }); const request = new Request("https://www.beiqiang.online/api/admin/repeat-order-opportunity", { method: "PATCH", headers: { Authorization: "Bearer correct", "Content-Type": "application/json" }, body: JSON.stringify({ reference, receivedAt: source.receivedAt, opportunityId: "ROP-ABCDEF012345", status: "qualified", owner: "Sales B", nextAction: "Prepare a focused replenishment quotation", nextActionDue: "2026-08-24", linkedInquiryReference: "", linkedOrderReference: "", note: "Quantity and destination are clear" }) }); const result = await handler({ request, env: { INQUIRY_ADMIN_TOKEN: "correct" } }); assert.equal(result.status, 200); assert.equal(saved.repeatOrderOpportunities[0].status, "qualified"); assert.equal(saved.repeatOrderOpportunities[0].history.length, 2); assert.equal(saved.repeatOrderOpportunities[0].history.at(-1).from, "submitted"); assert.equal(saved.owner, "Sales B");
});

test("conversion requires a linked new sourcing or formal-order record and completed opportunities stay immutable", async () => {
  const source = record(); source.repeatOrderOpportunities = [{ id: "ROP-ABCDEF012345", status: "formal_order_preparation", history: [] }]; let saved; const handler = createAdminRepeatOrderHandler({ getStoreImpl: () => ({ get: async () => source, setJSON: async (key, value) => { saved = structuredClone(value); } }) }); const make = (linkedOrderReference = "") => new Request("https://www.beiqiang.online/api/admin/repeat-order-opportunity", { method: "PATCH", headers: { Authorization: "Bearer correct", "Content-Type": "application/json" }, body: JSON.stringify({ reference, receivedAt: source.receivedAt, opportunityId: "ROP-ABCDEF012345", status: "converted", owner: "Sales A", nextAction: "Verify separate formal order", nextActionDue: "2026-08-24", linkedInquiryReference: "", linkedOrderReference, note: "" }) }); assert.equal((await handler({ request: make(), env: { INQUIRY_ADMIN_TOKEN: "correct" } })).status, 400); assert.equal((await handler({ request: make("TA-NEW-2"), env: { INQUIRY_ADMIN_TOKEN: "correct" } })).status, 200); source.repeatOrderOpportunities = saved.repeatOrderOpportunities; const reopen = new Request("https://www.beiqiang.online/api/admin/repeat-order-opportunity", { method: "PATCH", headers: { Authorization: "Bearer correct", "Content-Type": "application/json" }, body: JSON.stringify({ reference, receivedAt: source.receivedAt, opportunityId: "ROP-ABCDEF012345", status: "qualified", owner: "Sales A", nextAction: "Reopen", nextActionDue: "2026-08-25" }) }); assert.equal((await handler({ request: reopen, env: { INQUIRY_ADMIN_TOKEN: "correct" } })).status, 409);
});
