"use client";

import { useState } from "react";

export type FulfillmentCase = { id: string; source: string; status: string; category: string; title: string; facts: string; affectedScope: string; impact: string; proposedResolution: string; responseDue: string; createdAt: string; buyerDecision: string; buyerNote: string; buyerRespondedAt: string; resolvedAt: string; resolutionNote: string };
export type DeliveryFeedback = { id: string; action: string; category: string; note: string; trackingReference: string; createdAt: string };

export function FulfillmentCaseReview({ cases, reference, accessCode, onSaved, onStatus }: { cases: FulfillmentCase[]; reference: string; accessCode: string; onSaved: () => Promise<void>; onStatus: (message: string) => void }) {
  const pending = cases.find((item) => item.status === "awaiting_buyer"); const [note, setNote] = useState(""); const [saving, setSaving] = useState(false); if (!cases.length) return null;
  async function respond(decision: "acknowledge" | "request_revision") { if (!pending) return; if (decision === "request_revision" && note.trim().length < 2) { onStatus("Describe what should be revised before submitting."); return; } setSaving(true); onStatus("Saving your fulfillment response…"); try { const response = await fetch("/api/fulfillment-case-response", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reference, accessCode, caseId: pending.id, decision, note }) }); const result = await response.json().catch(() => ({})); if (!response.ok || !result.ok) throw new Error(result.message || "Your response could not be saved."); onStatus(result.message); await onSaved(); } catch (error) { onStatus(error instanceof Error ? error.message : "Your response could not be saved."); } finally { setSaving(false); } }
  return <section className="buyer-fulfillment-cases" id="fulfillment-case-review"><div><p className="eyebrow">FULFILLMENT EXCEPTION RECORD</p><h3>{pending ? "Your response is required" : "Fulfillment case history"}</h3><p>These records separate verified facts, affected scope, expected impact and proposed action. They do not silently rewrite the confirmed order.</p></div>{[...cases].reverse().map((item) => <article key={item.id} className={item.status === "awaiting_buyer" ? "pending" : ""}><div><strong>{item.id} · {item.title}</strong><span>{item.status.replaceAll("_", " ")}</span></div><p><b>Facts:</b> {item.facts}</p><p><b>Affected scope:</b> {item.affectedScope}</p><p><b>Expected impact:</b> {item.impact}</p><p><b>Proposed resolution:</b> {item.proposedResolution}</p><small>{item.category.replaceAll("_", " ")} · opened {new Date(item.createdAt).toLocaleString()} · response due {item.responseDue}</small>{item.buyerDecision && <p><b>Buyer response:</b> {item.buyerDecision.replaceAll("_", " ")}{item.buyerNote ? ` · ${item.buyerNote}` : ""}</p>}{item.resolvedAt && <p><b>Recorded resolution:</b> {item.resolutionNote} · {new Date(item.resolvedAt).toLocaleString()}</p>}</article>)}{pending ? <div className="buyer-fulfillment-response"><label>Response note<textarea rows={3} maxLength={1200} value={note} onChange={(event) => setNote(event.target.value)} placeholder="Add clarification, evidence requested or the exact change needed." /></label><div><button className="button" type="button" disabled={saving} onClick={() => respond("acknowledge")}>Acknowledge proposed resolution</button><button className="button button-secondary" type="button" disabled={saving} onClick={() => respond("request_revision")}>Request revision</button></div></div> : null}<small>Acknowledgement confirms receipt of the proposal only. It does not waive contractual rights, prove completion, or change price, specification, payment or delivery terms.</small></section>;
}

export function DeliveryFeedbackPanel({ status, feedback, reference, accessCode, onSaved, onStatus }: { status: string; feedback: DeliveryFeedback[]; reference: string; accessCode: string; onSaved: () => Promise<void>; onStatus: (message: string) => void }) {
  const [mode, setMode] = useState<"" | "issue">(""); const [category, setCategory] = useState("quality"); const [note, setNote] = useState(""); const [saving, setSaving] = useState(false); if (!["shipped", "completed"].includes(status)) return null; const received = feedback.some((item) => item.action === "received_as_expected");
  async function submit(action: "received_as_expected" | "report_issue") { if (action === "report_issue" && note.trim().length < 3) { onStatus("Describe what was received and what appears wrong."); return; } setSaving(true); onStatus("Saving your delivery feedback…"); try { const response = await fetch("/api/delivery-feedback", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reference, accessCode, action, category, note }) }); const result = await response.json().catch(() => ({})); if (!response.ok || !result.ok) throw new Error(result.message || "Delivery feedback could not be saved."); onStatus(result.message); setNote(""); setMode(""); await onSaved(); } catch (error) { onStatus(error instanceof Error ? error.message : "Delivery feedback could not be saved."); } finally { setSaving(false); } }
  return <section className="buyer-delivery-feedback" id="delivery-feedback"><div><p className="eyebrow">DELIVERY FEEDBACK</p><h3>Confirm receipt or report an issue</h3><p>Use the shipment reference shown in the order handoff. For an issue, add supporting photos or documents with the buyer file uploader.</p></div>{feedback.length ? <div className="buyer-delivery-history">{[...feedback].reverse().map((item) => <p key={`${item.id}-${item.createdAt}`}><strong>{item.action.replaceAll("_", " ")}</strong><span>{item.category ? `${item.category.replaceAll("_", " ")} · ` : ""}{new Date(item.createdAt).toLocaleString()}</span>{item.note && <small>{item.note}</small>}</p>)}</div> : null}<div className="buyer-delivery-actions"><button className="button" type="button" disabled={saving || received} onClick={() => submit("received_as_expected")}>{received ? "Receipt already recorded" : "Confirm received as expected"}</button><button className="button button-secondary" type="button" disabled={saving} onClick={() => setMode(mode === "issue" ? "" : "issue")}>Report a delivery issue</button></div>{mode === "issue" ? <div className="buyer-delivery-issue"><label>Issue category<select value={category} onChange={(event) => setCategory(event.target.value)}><option value="quantity">Quantity</option><option value="quality">Quality</option><option value="packing_labeling">Packing / labeling</option><option value="shipping_damage">Shipping damage</option><option value="document">Document</option><option value="other">Other</option></select></label><label>What was received and what is wrong?<textarea required rows={4} maxLength={1200} value={note} onChange={(event) => setNote(event.target.value)} /></label><button className="button" type="button" disabled={saving} onClick={() => submit("report_issue")}>Save issue report</button></div> : null}<small>Receipt confirmation is operational only and does not waive hidden-defect or contractual rights. An issue report starts review; it does not itself amend the Trade Assurance order or signed contract.</small></section>;
}
