import type { Metadata } from "next";
import SiteHeader from "../components/SiteHeader";
import SiteFooter from "../components/SiteFooter";

export const metadata: Metadata = { title: "Privacy Notice | Beiqiang Footwear", description: "How Beiqiang Footwear handles B2B sourcing inquiries, uploaded buyer files and optional first-party website analytics.", alternates: { canonical: "https://www.beiqiang.online/privacy/" } };

export default function PrivacyPage() {
  return <main><SiteHeader /><section className="legal-hero"><p className="eyebrow">PRIVACY NOTICE</p><h1>Clear handling of sourcing information.</h1><p>Effective 23 August 2026. This notice explains the website practices of Quanzhou Beiqiang Footwear &amp; Apparel Co., Ltd. It does not claim certification under any privacy framework and should be reviewed as laws and operations change.</p></section><article className="legal-content">
    <section><h2>What we collect</h2><p>When you request the line sheet or submit a B2B inquiry, we collect the contact, company, market, product direction, quantity, requirements and consent information you provide. If you upload buyer files, we store the file, its name, type, size and upload time with the inquiry. Private inquiry-thread messages, buyer-facing documents supplied by Beiqiang, product shortlists prepared for the inquiry and your selected styles or replacement criteria, structured sample-project status and buyer sample responses, quotation decisions and revision targets, buyer order-setup requests, order handoff and buyer-safe fulfillment updates are stored with the same record. A sample review round can store its physical sample reference, products, purpose, supplied deliverables, review scope, acceptance criteria, exclusions, decision, note and timestamps so later rounds do not overwrite earlier evidence. Quotation revision targets can include affected styles, price or quantity direction, trade term, delivery timing, payment, packing, labeling and sample requests. An order-setup request can include the legal purchasing company, purchasing contact, preferred formal-order channel, buyer PO reference, destination, requested timing and instructions you supply. The server also creates a request identifier and a shortened daily hash derived from the connection address for security and troubleshooting.</p></section>
    <section><h2>Why we use it</h2><p>We use this information to review product fit, prepare a focused product shortlist, recognize possible repeat business relationships, discuss samples, prepare quotations and formal order documents, answer sourcing questions, record agreed payment milestones and fulfillment progress, prevent abuse and manage the inquiry-to-order process. For a confirmed order, the website can retain accepted order versions, proposed critical changes, the business reason, changed fields, buyer decision, buyer-notification delivery status and operational update history so a later edit does not silently overwrite the earlier record. We may email the inquiry contact when a confirmed-order change requires a buyer decision; the email links to the private status lookup but does not include the private access code. Repeat-relationship signals are reviewed by authorized staff and do not automatically merge records or confirm identity. A shortlist choice records product interest only. We do not use it or an uploaded technical target as proof that Beiqiang can achieve unconfirmed requirements, and an order-setup request does not automatically create or confirm an order.</p></section>
    <section><h2>Optional first-party analytics</h2><p>If you choose “Accept analytics,” the site records limited events such as product view, comparison, quote-list action, line-sheet request/download and contact click, together with campaign parameters, landing page and referrer. If you choose “Essential only,” these optional events and first-touch attribution are not stored. The consent preference itself is stored on your device.</p></section>
    <section><h2>Device storage</h2><p>The quote shortlist and most recent inquiry access values may be stored on your device so you can continue the request. Do not use a shared device for confidential inquiry access. You can clear these values through browser site-data controls.</p></section>
    <section><h2>Sharing and transaction platforms</h2><p>Inquiry data is used by authorized Beiqiang personnel and relevant production or logistics participants only when needed for the sourcing project. When an order is handled through Alibaba Trade Assurance, Alibaba.com processes that order under its own terms and privacy practices.</p></section>
    <section><h2>Security and retention</h2><p>Buyer status uses a private access code whose hash is stored by the server. Internal inquiry access uses a separate administrator token. Authorized staff may revoke or restore website access to a buyer upload or buyer-facing document when a version is wrong, unsafe or no longer current; the reason and timestamp remain in the inquiry audit. Revocation blocks website download but does not itself delete the stored file. No internet system can be guaranteed completely secure. Records should be retained only while needed for the sourcing relationship, dispute handling and applicable business-record duties; permanent deletion should follow a reviewed retention process.</p></section>
    <section><h2>Your request</h2><p>To ask about, correct or request deletion of website inquiry information, email <a href="mailto:421345308@qq.com">421345308@qq.com</a> and include the inquiry reference. We may request reasonable verification before changing or deleting a record.</p></section>
  </article><SiteFooter /></main>;
}
