import type { Metadata } from "next";
import CapabilityPage, { type CapabilityPageData } from "../components/CapabilityPage";
export const metadata: Metadata = { title: "Footwear Sample & Order Process | Beiqiang Footwear", description: "Understand Beiqiang's B2B footwear path from product shortlist and specification check to sample, order confirmation, packing and shipping coordination.", alternates: { canonical: "https://www.beiqiang.online/sample-order-process/" } };
const data: CapabilityPageData = {
  eyebrow: "SAMPLE-BEFORE-BULK WORKFLOW", title: "Move from product interest to an order-ready specification.", introduction: "The website helps buyers shortlist and qualify products. Samples, quotations and bulk terms follow only after the selected style and high-impact order details are checked.", primaryCta: "Build a quote list", primaryHref: "/request-quote/",
  proofLabel: "WHY THE PROCESS MATTERS", proofTitle: "Each step removes a different sourcing uncertainty.", proofCopy: "Product images help with selection, but they cannot confirm every material, fit, packing or commercial requirement. The sample and order brief create the shared reference used for the next decision.",
  images: [{ src: "/catalog/bq002/01_main.jpg", alt: "BQ002 product evidence for sample selection", caption: "Product shortlist" }, { src: "/factory/sole-check.jpg", alt: "Footwear sole checking during product review", caption: "Specification check" }, { src: "/factory/stock-boxes.jpg", alt: "Footwear stock boxes and order handling", caption: "Order preparation" }],
  stepsTitle: "Five decisions from shortlist to shipment coordination.", steps: [{ title: "Shortlist", copy: "Select product codes or send a reference with the target market and sales channel." }, { title: "Specification check", copy: "Align size, color, material, quantity, packing and customization requirements." }, { title: "Sample discussion", copy: "Confirm sample availability, cost, delivery arrangement and what the sample will validate." }, { title: "Bulk confirmation", copy: "Finalize price, quantity, size ratio, packing, trade terms and timing after specification review." }, { title: "Check, pack and coordinate", copy: "Follow the agreed order reference through checking, packing and shipping handover." }],
  confirmedTitle: "What the website handles now", confirmed: ["Product discovery and comparison", "Product-specific inquiry capture", "Email notification and internal inquiry ledger", "WhatsApp, email and Alibaba.com handoff"], confirmTitle: "What needs direct commercial confirmation", confirm: ["Sample charge and delivery method", "Final FOB or other trade-term price", "Bulk quantity, packing and lead time", "Payment, shipping and transaction arrangement"],
  closingTitle: "Send enough context for the next decision.", closingCopy: "A product code plus market, quantity, size, color and timing information is more actionable than a one-line price request and helps the team respond faster.",
};
export default function SampleOrderProcessPage() { return <CapabilityPage data={data} />; }
