import type { Metadata } from "next";
import CapabilityPage, { type CapabilityPageData } from "../components/CapabilityPage";
export const metadata: Metadata = { title: "Footwear Checking & Packing | Beiqiang Footwear", description: "See real footwear checking, sorting and carton preparation evidence, plus the specifications buyers should confirm before bulk orders.", alternates: { canonical: "https://www.beiqiang.online/quality-packing/", languages: { en: "https://www.beiqiang.online/quality-packing/", "zh-CN": "https://www.beiqiang.online/zh/quality-packing/", "x-default": "https://www.beiqiang.online/quality-packing/" } } };
const data: CapabilityPageData = {
  chineseHref: "/zh/quality-packing/",
  eyebrow: "PRODUCT CHECKING & PACKING", title: "Make order details visible before cartons are ready.", introduction: "Product checking is most useful when buyer requirements are precise. We align the selected style, color, size ratio, material direction and packing brief before final commercial confirmation.", primaryCta: "Prepare an order brief",
  proofLabel: "CHECKING EVIDENCE", proofTitle: "Real handling, sorting and packing preparation.", proofCopy: "The photos show real footwear checking and carton preparation scenes. The exact inspection points and packing method still depend on the confirmed product and order requirements.",
  images: [{ src: "/factory-video-stills/shoe-packing.webp", alt: "A worker handling a finished pair before packing", caption: "Pair handling before packing" }, { src: "/factory-video-stills/packing-preparation.webp", alt: "Shoe-box wrapping and packing preparation", caption: "Shoe-box packing preparation" }, { src: "/factory-video-stills/assembly-line.webp", alt: "Shoes moving through a production-line handling station", caption: "Production-line handling" }],
  stepsTitle: "A practical pre-shipment checking sequence.", steps: [{ title: "Freeze the reference", copy: "Confirm the selected style, approved sample or agreed visual and specification reference." }, { title: "Match order details", copy: "Check color, size ratio, quantity allocation, labeling and packing instructions against the order brief." }, { title: "Review product handling", copy: "Use order-appropriate visual and physical checks before packing preparation." }, { title: "Coordinate packing and shipment", copy: "Confirm carton, marks, documents and shipping arrangement with the buyer or forwarder." }],
  confirmedTitle: "Visible in our current evidence", confirmed: ["Manual shoe handling and checking", "Batch sorting scenes", "Carton storage and packing preparation", "Style-specific product photo packages"], confirmTitle: "Must be defined for each order", confirm: ["Inspection criteria and tolerances", "Pair, box, label and carton requirements", "Size ratio and color allocation", "Carton marks, shipping documents and handover timing"],
  closingTitle: "Send the packing and checking requirements with your product shortlist.", closingCopy: "This lets the factory identify what can follow a standard arrangement and what needs special confirmation before quotation.",
};
export default function QualityPackingPage() { return <CapabilityPage data={data} />; }
