import type { Metadata } from "next";
import Link from "next/link";
import ChineseSiteFooter from "../../components/ChineseSiteFooter";
import ChineseSiteHeader from "../../components/ChineseSiteHeader";
import CommercialStartingPoints from "../../components/CommercialStartingPoints";

export const metadata: Metadata = { title: "B2B鞋类采购指南｜贝强鞋业", description: "从产品选款、样品评审和报价，到Alibaba Trade Assurance或合同、包装与发运交接，了解贝强B2B采购路径。", alternates: { canonical: "https://www.beiqiang.online/zh/buyer-guide/", languages: { en: "https://www.beiqiang.online/buyer-guide/", "zh-CN": "https://www.beiqiang.online/zh/buyer-guide/", "x-default": "https://www.beiqiang.online/buyer-guide/" } } };

const buyingSteps = [["选款", "比较真实图片、产品款号、已确认事实和报价前待确认项。"], ["定义需求", "提供市场、渠道、数量、颜色、尺码、品牌、包装和目标时间。"], ["评审样品", "书面约定样品需验证的材料、结构、适配和外观范围。"], ["确认报价", "书面对齐单价、数量、码比、包装、贸易条款、有效期和交期。"], ["建立正式订单", "规格接受后，通过经核验的Alibaba Trade Assurance订单或双方合同进行交易。"], ["跟进履约", "按已确认订单跟进付款记录、样品或生产、检查、包装和发运交接。"]] as const;
const tradeTerms = [["尚未确定", "提供目的地、数量、包装方向和紧急程度，先判断报价所需资料。"], ["EXW", "货物在约定提货点交付，后续安排通常由买家指定物流方处理，以书面约定为准。"], ["FOB", "适用于送至约定装运港的海运或内河运输；主运费、目的港费用和进口安排除非书面说明，否则不包含。"], ["FCA", "适用于在约定地点向买家指定承运人交货，包括许多空运或多式联运场景。"], ["申请DDP评估", "必须提供准确目的地、数量、箱规、包装和时间；关税、税费、清关和当地派送仅在货代书面确认后纳入。"]] as const;
const faqs = [["只凭产品图片能得到最终价格吗？", "不能可靠确定。最终价格取决于款式、已确认材料、数量、码比、包装、定制和贸易要求。"], ["样品通常如何寄送？", "通常讨论快递寄样；确认安排或费用前，需要收件国家、邮编、样品数量和地址资料。"], ["能否报价送到Amazon FBA？", "提供仓库国家或代码、数量、包装、箱规、毛重和时间后可以评估，但不能提前保证清关结果。"], ["接受报价是否等于已下单？", "不是。报价是商业建议；双方确认所需文件并建立Trade Assurance或合同交易后，订单才正式开始。"]] as const;

export default function ChineseBuyerGuidePage() { return <main><ChineseSiteHeader englishHref="/buyer-guide/" />
  <section className="buyer-guide-hero"><div><p className="eyebrow">B2B鞋类采购指南</p><h1>在大货开始前，弄清每一个关键决定。</h1><p>从产品发现、样品、报价、正式交易到发运交接，使用一条证据清楚的路径。商业条件按具体项目确认，不从目录页默认推断。</p><div className="hero-actions"><Link className="button" href="/zh/request-quote/">建立可报价采购需求</Link><Link className="text-link" href="/zh/products/">比较全部产品 →</Link></div></div><aside><small>有效的第一条信息</small><strong>产品款号 + 目标市场 + 样品/大货数量 + 尺码/颜色 + 实际目的地。</strong><p>这些资料能帮助工厂回答下一个商业问题，而不是只回复笼统价格。</p></aside></section>
  <CommercialStartingPoints locale="zh" />
  <section className="section buyer-guide-steps"><div className="section-heading"><div><p className="eyebrow">从选款到交接</p><h2>六个决定，一条可追溯采购记录。</h2></div><p>网站把产品证据、消息、报价版本、交易参考和买家安全进度连接到原始询盘。</p></div><div>{buyingSteps.map(([title, copy], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="buyer-guide-brief"><div><p className="eyebrow eyebrow-light">询问运费前</p><h2>提供会改变物流报价的事实。</h2><p>目标市场不一定等于交货目的地；请提供实际国家、城市、港口、邮编或FBA仓库方向。</p></div><ul><li>产品款号与数量</li><li>样品或大货</li><li>目的地与交付类型</li><li>码比和包装方向</li><li>期望发运窗口</li><li>买家货代或工厂询价</li></ul></section>
  <section className="section buyer-guide-terms"><div className="section-heading compact"><div><p className="eyebrow">贸易条款起点</p><h2>先选择偏好，再确认指定地点。</h2></div></div><div className="trade-term-table"><div><strong>偏好</strong><strong>首次评审含义</strong></div>{tradeTerms.map(([term, explanation]) => <div key={term}><strong>{term}</strong><p>{explanation}</p></div>)}</div><p className="buyer-guide-boundary">这些说明仅支持首次询盘，不替代最终Incoterm、指定地点、货代指令、清关建议或签署文件。</p></section>
  <section className="buyer-guide-transaction"><article><p className="eyebrow eyebrow-light">正式交易路径</p><h2>把付款放在经核验的订单渠道。</h2><p>样品/规格和商业条款确认后，通过Alibaba Trade Assurance或双方合同记录交易。网站不收集银行卡、网银密码或验证码。</p><Link className="button button-light" href="/zh/sample-order-process/">查看样品与订单流程</Link></article><article><p className="eyebrow">买家控制</p><h2>保存参考号和私密访问码。</h2><p>每条已保存需求均获得参考号和私密访问码，用于查看进度、消息、已签发报价、交易文件和履约更新。</p><Link className="text-link" href="/zh/inquiry-status/">打开私密项目进度 →</Link></article></section>
  <section className="section buyer-guide-faq"><div className="section-heading compact"><div><p className="eyebrow">商业常见问题</p><h2>在订单文件前确认的问题。</h2></div></div><div>{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
  <section className="section capability-closing"><div><p className="eyebrow">下一步</p><h2>把选款变成完整采购需求。</h2><p>添加候选款、数量、颜色和尺码，再说明目的地与贸易条款偏好；贝强将审核下一步可以确认的内容。</p></div><div className="hero-actions"><Link className="button" href="/zh/request-quote/">准备询价</Link><a className="text-link" href="https://wa.me/8618959805256" target="_blank" rel="noreferrer">通过WhatsApp沟通 →</a></div></section><ChineseSiteFooter /></main>; }
